//============================================================================
//  DECO Cassette System - Main CPU address decode, read mux, and write strobes
//
//  This module implements the primary 6502 address decode, read data mux,
//  and write strobe generation for the DECO Cassette arcade core.
//
//  Based on MAME src/mame/deco/decocass.cpp:
//    - decocass_map (lines 88-127): address map decode
//    - decocrom_map (lines 130-134): extended banking (not yet implemented)
//
//  The CPU clock (ce_main @ 750 kHz = HCLK4) is generated by the clock_div
//  module and drives the deco222 wrapper around the T65 6502 core. This
//  matches MAME's DECO_222(config, m_maincpu, HCLK4) at decocass.cpp:1018.
//
//  Memory map summary (per decocass_map):
//    $0000-$5FFF: rambase (24K work RAM)
//    $6000-$BFFF: charram (write triggers char-dirty)
//    $C000-$C3FF: fgvideoram
//    $C400-$C7FF: colorram
//    $C800-$CBFF: mirror of fgvideoram (swizzled: a[4:0]<->a[9:5])
//    $CC00-$CFFF: mirror of colorram (swizzled)
//    $D000-$D7FF: tileram (write triggers tile-dirty)
//    $D800-$DBFF: objectram
//    $E000-$E0FF: paletteram
//    $E300, $E301: DSW1/DSW2 + watchdog
//    $E302-$E417: control registers
//    $E500-$E5FF: dongle / 8041 I/O
//    $E600-$E6FF: input mux
//    $E700-$E701: sound data/ack
//    $F000-$FFFF: BIOS ROM (4K, loaded by rom_loader in task 25)
//
//============================================================================

module decocass (
    input  wire        clk_sys,           // 96 MHz system clock
    input  wire        ce_main,           // 750 kHz CPU clock enable (HCLK4 = MASTER/16, per MAME decocass.cpp:1018)
    input  wire        reset,

    // CPU interface (connected to deco222 wrapper)
    output wire [15:0] cpu_addr,
    output wire [7:0]  cpu_dout,
    output wire        cpu_rw_n,          // 1=read, 0=write
    output wire        cpu_sync,          // opcode fetch strobe

    // Write strobes (output for downstream modules)
    output wire        cpu_we_ram,        // rambase
    output wire        cpu_we_charram,    // charram
    output wire        cpu_we_fgvram,     // fgvideoram + mirror
    output wire        cpu_we_colram,     // colorram + mirror
    output wire        cpu_we_tilram,     // tileram
    output wire        cpu_we_objram,     // objectram
    output wire        cpu_we_palram,     // paletteram

    // Control register strobes (for E3xx/E4xx writes)
    output wire        cpu_we_e3xx,       // $E300-$E301 watchdog
    output wire        cpu_we_e4xx,       // $E400-$E417 various controls
    output wire        cpu_we_e414,       // $E414 sound command write (audio NMI + latch)
    output wire        cpu_we_e5xx,       // $E500-$E5FF dongle write
    output wire        cpu_re_e5xx,       // $E500-$E5FF dongle read
    output wire        cpu_we_e6xx,       // $E600-$E6FF input (read-only, but expose strobe)
    output wire        cpu_we_e7xx,       // $E700-$E701 sound (read-only)
    output wire        cpu_re_e700,       // $E700 sound data read
    output wire        cpu_re_e701,       // $E701 sound ack read

    // Data inputs from peripherals (for read mux, stubbed as 0xFF/0x00 for now)
    input  wire [7:0]  sound_data,        // from audio subsystem (task 13)
    input  wire [7:0]  sound_ack,         // from audio subsystem (task 13)
    input  wire [7:0]  e5xx_dongle_q,     // from dongle (task 24)
    input  wire [7:0]  input_q,           // from input mux (task 26)
    input  wire [7:0]  bios_q,            // from BIOS ROM BRAM
    input  wire [7:0]  dsw1,              // DSW1 ($E300 read; bit 7 overridden by vblank)
    input  wire [7:0]  dsw2,              // DSW2 ($E301 read)
    input  wire        vblank,            // vblank status (active high in vblank) — DSW1[7]

    input  wire        coin_in,           // active-high coin press (joystick_0[14]). MAME's
                                          // INPUT_CHANGED_MEMBER(coin_inserted) asserts main
                                          // CPU NMI on falling edge of coin (button press,
                                          // newval=0 active-low). Translated: rising edge of
                                          // active-high `coin_in` here = coin press = NMI.


    // BRAM read data (address buses are generated below)
    input  wire [7:0]  ram_q,
    input  wire [7:0]  charram_q,
    input  wire [7:0]  fgvram_q,
    input  wire [7:0]  colram_q,
    input  wire [7:0]  tilram_q,
    input  wire [7:0]  objram_q,
    input  wire [7:0]  palram_q,

    // BRAM address/write buses
    output wire [14:0] ram_addr_w,
    output wire        ram_we_w,
    output wire [7:0]  ram_dw,

    // CHARRAM-CPU-RW-FIX-2026-06-07: widened 13->15 bits. The CPU-readback charram must be a
    // LINEAR 24 KB ($6000-$BFFF) so a byte written reads back identically (the $4A7D RLE
    // decompressor reads its source from charram). 13-bit aliased all 3 planes into 8 KB.
    // DIAG-REVERT: original below.
    // output wire [12:0] charram_addr_w,    // 13-bit (8 KB per plane; charram is 3 planes × 8 KB)
    output wire [14:0] charram_addr_w,    // 15-bit linear: plane0=$0000 plane1=$2000 plane2=$4000
    output wire        charram_we_p0,     // plane 0 ($6000-$7FFF) write enable
    output wire        charram_we_p1,     // plane 1 ($8000-$9FFF) write enable
    output wire        charram_we_p2,     // plane 2 ($A000-$BFFF) write enable
    output wire [7:0]  charram_dw,

    output wire [9:0]  fgvram_addr_w,
    output wire        fgvram_we_w,
    output wire [7:0]  fgvram_dw,

    output wire [9:0]  colram_addr_w,
    output wire        colram_we_w,
    output wire [7:0]  colram_dw,

    output wire [10:0] tilram_addr_w,
    output wire        tilram_we_w,
    output wire [7:0]  tilram_dw,

    output wire [9:0]  objram_addr_w,
    output wire        objram_we_w,
    output wire [7:0]  objram_dw,

    output wire [7:0]  palram_addr_w,
    output wire        palram_we_w,
    output wire [7:0]  palram_dw,

    output wire [11:0] bios_addr_w,
    output wire        bios_we_w,
    output wire [7:0]  bios_dw,

    // Latched control register outputs (for future phases)
    output wire [7:0]  mode_set_reg,      // $E402
    output wire [7:0]  back_h_shift_reg,  // $E403
    output wire [7:0]  back_vl_shift_reg, // $E404
    output wire [7:0]  back_vr_shift_reg, // $E405
    output wire [7:0]  part_h_shift_reg,  // $E406 (headlight)
    output wire [7:0]  part_v_shift_reg,  // $E407 (headlight)
    output wire [7:0]  color_center_bot_reg, // $E410
    output wire [7:0]  center_h_shift_space_reg, // $E411
    output wire [7:0]  center_v_shift_reg,  // $E412
    output wire [7:0]  coin_counter_reg,  // $E413
    output wire [7:0]  nmi_reset_reg      // $E417
);

    //------------------------------------------------------------------------
    // Instantiate DECO-222 CPU wrapper
    // Reference: rtl/cpu/deco222.v
    // Enable input: ce_main (750 kHz = HCLK4, active for one clk_sys cycle)
    //------------------------------------------------------------------------

    wire [15:0] cpu_addr_int;
    wire [7:0]  cpu_dout_int;
    wire        cpu_rw_n_int;
    wire        cpu_sync_int;
    wire [7:0]  cpu_din;              // local: mux output -> CPU .di

    deco222 cpu (
        .clk_sys (clk_sys),
        .ce      (ce_main),           // 750 kHz CPU enable (HCLK4)
        .reset   (reset),
        .nmi_n   (~cpu_nmi_req),       // VBLANK-rising NMI; cleared by $E417 write
        .irq_n   (1'b1),               // No IRQ input for now
        .rdy     (1'b1),               // Always ready
        .addr    (cpu_addr_int),
        .di      (cpu_din),
        .do      (cpu_dout_int),
        .rw_n    (cpu_rw_n_int),
        .sync    (cpu_sync_int)
    );

    //------------------------------------------------------------------------
    // Main CPU NMI generation — MAME-faithful (decocass_m.cpp:150-159).
    //
    // 2026-05-17 — REWRITE. The previous implementation asserted NMI on every
    // VBLANK rising edge, citing "per the hardware." But MAME asserts main-CPU
    // NMI EXCLUSIVELY on coin insert (`INPUT_CHANGED_MEMBER(coin_inserted)` at
    // decocass_m.cpp:155-159 → `set_input_line(NMI, ASSERT_LINE)` on falling
    // edge of coin button). The $E417 write (decocass_nmi_reset_w, line 150)
    // clears it. No screen_vblank_callback / set_periodic_int / vblank-NMI
    // binding exists anywhere in MAME's decocass machine config.
    //
    // The vblank-NMI was almost certainly hammering BIOS at 60 Hz during early
    // init — before the NMI vector is valid, before the stack pointer is set,
    // or before the NMI handler can safely run. Symptom: BIOS completes the
    // palette-clear phase (visible via swatch screenshot) then never advances
    // to color setup or logo draw. With NMI removed from the init path, BIOS
    // should reach its "wait for coin" state and display the DECO logo.
    //
    // Coin signal is active-high `coin_in` (from `joystick_0[14]` in the
    // wrapper). MAME treats coin as active-low and triggers on falling edge;
    // translated here as rising edge of active-high coin_in = coin press.
    //------------------------------------------------------------------------
    reg coin_d;
    reg cpu_nmi_req;
    reg vblank_d;   // DIAG-REVERT-2026-05-29: vblank edge detect for restored vblank-NMI

    always @(posedge clk_sys) begin
        if (reset) begin
            coin_d      <= 1'b0;
            cpu_nmi_req <= 1'b0;
            vblank_d    <= 1'b0;   // DIAG-REVERT-2026-05-29
        end else begin
            coin_d   <= coin_in;
            vblank_d <= vblank;    // DIAG-REVERT-2026-05-29
            // DIAG-REVERT-2026-05-29: RESTORE vblank-NMI (the prior session removed it,
            // lines 169-182). Diagnostic shows the main 6502 spins in $Fxxx touching NO
            // peripherals ($E5xx/$E414/$E700/$E701 all black) -> it's waiting on a
            // RAM value an interrupt should update, and its only NMI is coin. The
            // original DECO code NMI'd every vblank (the main loop is vblank-driven, like
            // Kyugo). Testing coin OR vblank-rising. Revert = restore the coin-only line.
            // AUDIT-2026-05-30: REVERTED the restored vblank-NMI back to coin-only. MAME proof:
            // DECO main CPU NMI is coin-ONLY (decocass_m.cpp:158), has NO IRQ, and NO vblank
            // interrupt — the BIOS POLLS vblank via DSW1[7]/$E300 (decocass.cpp:214, already wired
            // in cpu_din_mux ~line 454). "vblank-driven like Kyugo" is disproven; the vblank-NMI is
            // the phantom-NMI pitfall ([[Wrong interrupt line stalls boot]]) — hammers BIOS at 60Hz.
            // Restore the vblank test = `|| (vblank && !vblank_d)` below.
            if (coin_in && !coin_d)
            // if ((coin_in && !coin_d) || (vblank && !vblank_d))
                cpu_nmi_req <= 1'b1;
            // CPU write to $E417 clears it (decocass_nmi_reset_w).
            else if (cpu_addr_int == 16'hE417 && !cpu_rw_n_int && ce_main)
                cpu_nmi_req <= 1'b0;
        end
    end

    assign cpu_addr  = cpu_addr_int;
    assign cpu_dout  = cpu_dout_int;
    assign cpu_rw_n  = cpu_rw_n_int;
    assign cpu_sync  = cpu_sync_int;

    //------------------------------------------------------------------------
    // Address decode (lines 88-127 of decocass.cpp)
    //------------------------------------------------------------------------

    wire sel_ram      = (cpu_addr_int <  16'h6000);
    wire sel_charram  = (cpu_addr_int >= 16'h6000) && (cpu_addr_int < 16'hC000);
    wire sel_fgvram   = (cpu_addr_int[15:10] == 6'b110000);  // C000-C3FF
    wire sel_colram   = (cpu_addr_int[15:10] == 6'b110001);  // C400-C7FF
    wire sel_fgvram_m = (cpu_addr_int[15:10] == 6'b110010);  // C800-CBFF mirror
    wire sel_colram_m = (cpu_addr_int[15:10] == 6'b110011);  // CC00-CFFF mirror
    wire sel_tilram   = (cpu_addr_int[15:11] == 5'b11010);   // D000-D7FF
    wire sel_objram   = (cpu_addr_int[15:10] == 6'b110110);  // D800-DBFF
    wire sel_palram   = (cpu_addr_int[15:8]  == 8'hE0);      // E000-E0FF
    wire sel_e3       = (cpu_addr_int[15:8]  == 8'hE3);      // E300-E3FF
    wire sel_e4       = (cpu_addr_int[15:8]  == 8'hE4);      // E400-E4FF
    wire sel_e5       = (cpu_addr_int[15:8]  == 8'hE5);      // E500-E5FF
    wire sel_e6       = (cpu_addr_int[15:8]  == 8'hE6);      // E600-E6FF
    wire sel_e7       = (cpu_addr_int[15:8]  == 8'hE7);      // E700-E7FF
    wire sel_rom      = (cpu_addr_int[15:12] == 4'hF);       // F000-FFFF

    //------------------------------------------------------------------------
    // Mirror-swap function (lines 80-86 of task spec)
    // For C800/CC00 addresses: swap a[4:0] <-> a[9:5]
    //------------------------------------------------------------------------

    function [9:0] swiz;
        input [9:0] a;
        swiz = { a[4:0], a[9:5] };
    endfunction

    //------------------------------------------------------------------------
    // Address routing to BRAMs
    //------------------------------------------------------------------------

    // rambase: $0000-$5FFF (24K, 15-bit address space)
    assign ram_addr_w   = cpu_addr_int[14:0];
    assign ram_dw       = cpu_dout_int;
    assign ram_we_w     = (sel_ram && !cpu_rw_n_int && ce_main);

    // charram: $6000-$BFFF (24 KB total — 3 planes × 8 KB).
    //
    // 2026-05-17 — REWRITE. Previous version shipped a single 14-bit address
    // (`cpu_addr[13:0]`) into a 12-bit charram BRAM, collapsing 3 planes worth
    // of writes into a single 4 KB region. Per MAME `decocass.cpp:939-948`
    // `charlayout`, the FG character set is 3 planes × 1024 tiles × 8 bytes
    // = 24 KB, and each plane occupies a distinct 8 KB CPU window:
    //   Plane 0: $6000-$7FFF    cpu_addr[15:13] == 3'b011
    //   Plane 1: $8000-$9FFF    cpu_addr[15:13] == 3'b100
    //   Plane 2: $A000-$BFFF    cpu_addr[15:13] == 3'b101
    // Now decode the upper bits into three separate write-enables and ship
    // a 13-bit byte-offset within the plane.
    wire   sel_charram_p0 = sel_charram && (cpu_addr_int[15:13] == 3'b011);
    wire   sel_charram_p1 = sel_charram && (cpu_addr_int[15:13] == 3'b100);
    wire   sel_charram_p2 = sel_charram && (cpu_addr_int[15:13] == 3'b101);

    // CHARRAM-CPU-RW-FIX-2026-06-07: linear offset so $6000-$BFFF round-trips as 24 KB. The per-plane
    // write enables (we_p0/p1/p2) still split the planes; with the linear address each plane lands in
    // its own 8 KB band (plane0=$0000-$1FFF, plane1=$2000-$3FFF, plane2=$4000-$5FFF), so a CPU write
    // and a later CPU read at the SAME $6000-$BFFF address hit the SAME cell (no more 8 KB aliasing).
    // (16-bit subtract; result $0000-$5FFF in range, MSB truncates losslessly into the 15-bit bus.)
    // DIAG-REVERT: original below.
    // assign charram_addr_w = cpu_addr_int[12:0];
    assign charram_addr_w = cpu_addr_int - 16'h6000;
    assign charram_dw     = cpu_dout_int;
    assign charram_we_p0  = (sel_charram_p0 && !cpu_rw_n_int && ce_main);
    assign charram_we_p1  = (sel_charram_p1 && !cpu_rw_n_int && ce_main);
    assign charram_we_p2  = (sel_charram_p2 && !cpu_rw_n_int && ce_main);

    // fgvideoram and mirror: $C000-$C3FF, $C800-$CBFF (1K)
    // Normal: address = cpu_addr[9:0]
    // Mirror: address = swiz(cpu_addr[9:0])
    wire [9:0] fgvram_addr_eff = sel_fgvram_m ? swiz(cpu_addr_int[9:0]) : cpu_addr_int[9:0];
    assign fgvram_addr_w = fgvram_addr_eff;
    assign fgvram_dw     = cpu_dout_int;
    assign fgvram_we_w   = ((sel_fgvram || sel_fgvram_m) && !cpu_rw_n_int && ce_main);

    // colorram and mirror: $C400-$C7FF, $CC00-$CFFF (1K)
    wire [9:0] colram_addr_eff = sel_colram_m ? swiz(cpu_addr_int[9:0]) : cpu_addr_int[9:0];
    assign colram_addr_w = colram_addr_eff;
    assign colram_dw     = cpu_dout_int;
    assign colram_we_w   = ((sel_colram || sel_colram_m) && !cpu_rw_n_int && ce_main);

    // tileram: $D000-$D7FF (2K, 11-bit address space)
    assign tilram_addr_w = cpu_addr_int[10:0];
    assign tilram_dw     = cpu_dout_int;
    assign tilram_we_w   = (sel_tilram && !cpu_rw_n_int && ce_main);

    // objectram: $D800-$DBFF (1K, 10-bit address space)
    assign objram_addr_w = cpu_addr_int[9:0];
    assign objram_dw     = cpu_dout_int;
    assign objram_we_w   = (sel_objram && !cpu_rw_n_int && ce_main);

    // paletteram: $E000-$E0FF (CPU readback dpram, no XOR — MAME stores
    // the raw byte at `m_paletteram[offset]` so CPU readback returns the
    // last-written value at the same offset. The XOR transform lives in
    // the video-side palette (see Arcade-DECOCassette.sv video_palette_inst).
    assign palram_addr_w = cpu_addr_int[7:0];
    assign palram_dw     = cpu_dout_int;
    assign palram_we_w   = (sel_palram && !cpu_rw_n_int && ce_main);

    // BIOS ROM: $F000-$FFFF (4K, 12-bit address space)
    // ROM is read-only, but expose a write port for the rom_loader in task 25
    assign bios_addr_w = cpu_addr_int[11:0];
    assign bios_dw     = cpu_dout_int;
    assign bios_we_w   = (sel_rom && !cpu_rw_n_int && ce_main);

    //------------------------------------------------------------------------
    // Write strobes (for downstream module consumption)
    // Each strobe pulses for one ce_main cycle when the CPU writes to that region
    //------------------------------------------------------------------------

    assign cpu_we_ram    = ram_we_w;
    assign cpu_we_charram = charram_we_p0 | charram_we_p1 | charram_we_p2;
    assign cpu_we_fgvram = fgvram_we_w;
    assign cpu_we_colram = colram_we_w;
    assign cpu_we_tilram = tilram_we_w;
    assign cpu_we_objram = objram_we_w;
    assign cpu_we_palram = palram_we_w;
    assign cpu_we_e3xx   = (sel_e3 && !cpu_rw_n_int && ce_main);
    assign cpu_we_e4xx   = (sel_e4 && !cpu_rw_n_int && ce_main);
    assign cpu_we_e414   = (cpu_addr_int == 16'hE414 && !cpu_rw_n_int && ce_main);
    assign cpu_we_e5xx   = (sel_e5 && !cpu_rw_n_int && ce_main);
    assign cpu_we_e6xx   = (sel_e6 && !cpu_rw_n_int && ce_main);  // read-only, but expose for completeness
    assign cpu_we_e7xx   = (sel_e7 && !cpu_rw_n_int && ce_main);  // read-only

    // Read strobes — one ce_main pulse per CPU read. Without these:
    //   - $E5xx: MCU/dongle never sees rd_n; Type1/3 dongle counters stuck → BIOS dongle handshake hangs (white screen)
    //   - $E700/$E701: sound ack flag never clears; main CPU may spin on sound handshake
    assign cpu_re_e5xx   = (sel_e5                       &&  cpu_rw_n_int && ce_main);
    assign cpu_re_e700   = (cpu_addr_int == 16'hE700     &&  cpu_rw_n_int && ce_main);
    assign cpu_re_e701   = (cpu_addr_int == 16'hE701     &&  cpu_rw_n_int && ce_main);

    //------------------------------------------------------------------------
    // Control register latch (for outputs consumed by future phases)
    // These capture register writes and hold the value until overwritten.
    // Reference: decocass.cpp lines 105-118 for register semantics.
    //------------------------------------------------------------------------

    reg [7:0] mode_set;
    reg [7:0] back_h_shift;
    reg [7:0] back_vl_shift;
    reg [7:0] back_vr_shift;
    reg [7:0] part_h_shift;
    reg [7:0] part_v_shift;
    reg [7:0] color_center_bot;
    reg [7:0] center_h_shift_space;
    reg [7:0] center_v_shift;
    reg [7:0] coin_counter;
    reg [7:0] nmi_reset;

    always @(posedge clk_sys) begin
        if (reset) begin
            mode_set             <= 8'h00;
            back_h_shift         <= 8'h00;
            back_vl_shift        <= 8'h00;
            back_vr_shift        <= 8'h00;
            part_h_shift         <= 8'h00;
            part_v_shift         <= 8'h00;
            color_center_bot     <= 8'h00;
            center_h_shift_space <= 8'h00;
            center_v_shift       <= 8'h00;
            coin_counter         <= 8'h00;
            nmi_reset            <= 8'h00;
        end else if (ce_main && !cpu_rw_n_int) begin
            // Latch register writes at each CPU write cycle
            if (cpu_addr_int == 16'hE402) mode_set             <= cpu_dout_int;
            if (cpu_addr_int == 16'hE403) back_h_shift         <= cpu_dout_int;
            if (cpu_addr_int == 16'hE404) back_vl_shift        <= cpu_dout_int;
            if (cpu_addr_int == 16'hE405) back_vr_shift        <= cpu_dout_int;
            if (cpu_addr_int == 16'hE406) part_h_shift         <= cpu_dout_int;
            if (cpu_addr_int == 16'hE407) part_v_shift         <= cpu_dout_int;
            if (cpu_addr_int == 16'hE410) color_center_bot     <= cpu_dout_int;
            if (cpu_addr_int == 16'hE411) center_h_shift_space <= cpu_dout_int;
            if (cpu_addr_int == 16'hE412) center_v_shift       <= cpu_dout_int;
            if (cpu_addr_int == 16'hE413) coin_counter         <= cpu_dout_int;
            if (cpu_addr_int == 16'hE417) nmi_reset            <= cpu_dout_int;
        end
    end

    assign mode_set_reg            = mode_set;
    assign back_h_shift_reg        = back_h_shift;
    assign back_vl_shift_reg       = back_vl_shift;
    assign back_vr_shift_reg       = back_vr_shift;
    assign part_h_shift_reg        = part_h_shift;
    assign part_v_shift_reg        = part_v_shift;
    assign color_center_bot_reg    = color_center_bot;
    assign center_h_shift_space_reg = center_h_shift_space;
    assign center_v_shift_reg      = center_v_shift;
    assign coin_counter_reg        = coin_counter;
    assign nmi_reset_reg           = nmi_reset;

    //------------------------------------------------------------------------
    // Read mux (lines 88-120 of task spec)
    // Multiplexes CPU data input from all readable regions.
    // Reference: decocass.cpp lines 88-127 for read sources.
    //------------------------------------------------------------------------

    reg [7:0] cpu_din_mux;

    always @* begin
        casez (cpu_addr_int)
            // RAM: $0000-$5FFF (lines 94-97 of spec)
            // NOTE: first arm narrowed to 00xx (was 0xxx) so $6000-$7FFF
            // correctly routes to charram_q below, per decocass.cpp memory map.
            16'b00??_????_????_????,
            16'b0100_????_????_????,
            16'b0101_????_????_????:        cpu_din_mux = ram_q;

            // Charram: $6000-$BFFF (lines 98-102 of spec)
            16'b011?_????_????_????,
            16'b1000_????_????_????,
            16'b1001_????_????_????,
            16'b1010_????_????_????,
            16'b1011_????_????_????:        cpu_din_mux = charram_q;

            // fgvideoram: $C000-$C3FF (line 103 of spec)
            16'b1100_00??_????_????:        cpu_din_mux = fgvram_q;

            // colorram: $C400-$C7FF (line 104 of spec)
            16'b1100_01??_????_????:        cpu_din_mux = colram_q;

            // fgvideoram mirror: $C800-$CBFF (line 105 of spec)
            16'b1100_10??_????_????:        cpu_din_mux = fgvram_q;

            // colorram mirror: $CC00-$CFFF (line 106 of spec)
            16'b1100_11??_????_????:        cpu_din_mux = colram_q;

            // tileram: $D000-$D7FF (line 107 of spec)
            16'b1101_0???_????_????:        cpu_din_mux = tilram_q;

            // objectram: $D800-$DBFF (line 108 of spec)
            16'b1101_10??_????_????:        cpu_din_mux = objram_q;

            // paletteram: $E000-$E0FF (line 109 of spec)
            16'b1110_0000_????_????:        cpu_din_mux = palram_q;

            // DSW1: $E300 (line 110 of spec)
            // Per MAME decocass.cpp PORT_START("DSW1"): bit[7] is VBLANK custom port,
            // bits[6:0] are DIP switches. BIOS polls $E300[7] for vblank → if stubbed 0,
            // BIOS spins forever waiting for vblank. Active-high vblank.
            16'hE300:                       cpu_din_mux = {vblank, dsw1[6:0]};

            // DSW2: $E301 (line 111 of spec)
            16'hE301:                       cpu_din_mux = dsw2;

            // Sound command read: $E414 returns constant 0xC0 (line 112 of spec)
            16'hE414:                       cpu_din_mux = 8'hC0;

            // Sound data: $E700 (line 113 of spec)
            16'hE700:                       cpu_din_mux = sound_data;

            // Sound ack: $E701 (line 114 of spec)
            16'hE701:                       cpu_din_mux = sound_ack;

            // Dongle / 8041: $E500-$E5FF (line 115 of spec)
            16'b1110_0101_????_????:        cpu_din_mux = e5xx_dongle_q;

            // Input mux: $E600-$E6FF (line 116 of spec)
            16'b1110_0110_????_????:        cpu_din_mux = input_q;

            // BIOS ROM: $F000-$FFFF (line 117 of spec)
            16'b1111_????_????_????:        cpu_din_mux = bios_q;

            // Default: return 0xFF for unmapped addresses (line 118 of spec)
            default:                        cpu_din_mux = 8'hFF;
        endcase
    end

    //------------------------------------------------------------------------
    // Forward muxed read data back to deco222 CPU wrapper
    //------------------------------------------------------------------------

    assign cpu_din = cpu_din_mux;

endmodule
