// DECO Cassette audio CPU (M6502) + NMI generator.
//
// References:
//  - decocass.cpp lines 137-149: audio_cpu memory map
//  - decocass.cpp lines 1015-1040: audio CPU clock (HCLK1/2 = 500 kHz), NMI timer config
//  - decocass_m.cpp lines 117-148: NMI enable register and sound-data ack semantics
//
// Memory map:
//  $0000-$0FFF (4K)    : work RAM
//  $1000-$17FF         : NMI enable register (any write/read sets audio_nmi_enabled=1)
//  $1800-$1FFF         : sound-data ack reset (clears sound_ack bit 0x40)
//  $2000-$2FFF         : AY1 data write
//  $4000-$4FFF         : AY1 address write
//  $6000-$6FFF         : AY2 data write
//  $8000-$8FFF         : AY2 address write
//  $A000-$AFFF         : read sound command from main (also clears audio IRQ)
//  $C000-$CFFF         : write sound data to main (also sets sound_ack)
//  $F800-$FFFF (2K)    : audio BIOS ROM
//
// NMI generation:
//  Every 8 scanlines, NMI toggles. Generated by latching vcnt[3] at hcounter==0
//  when audio_nmi_enabled=1. NMI is level-triggered: nmi_n = ~(audio_nmi_enabled & audio_nmi_state).

module audio_cpu (
    input  wire        clk_sys,           // 96 MHz system clock
    input  wire        reset,             // active-high reset
    input  wire        ce_audio,          // 500 kHz clock enable (from clock_div.v)
    input  wire        ce_pix,            // pixel clock enable (= ce_hclk)

    // Interrupt inputs
    input  wire        audio_irq_set,     // from main CPU ($E414 write)

    // Scanline/pixel timing (from video_timing.v)
    input  wire        hcounter_eq_0,     // start of new scanline
    input  wire [8:0]  vcounter,          // vertical counter [0..261]

    // ROM loader interface (task 25)
    input  wire        rom_we,            // write enable for audio BIOS ROM
    input  wire [10:0] rom_addr_w,        // write address (11-bit for 2K)
    input  wire [7:0]  rom_data_w,        // write data

    // AY1/AY2 interface (to task 13)
    output wire        ay1_data_we,       // AY1 data write strobe
    output wire        ay1_addr_we,       // AY1 address write strobe
    output wire        ay2_data_we,       // AY2 data write strobe
    output wire        ay2_addr_we,       // AY2 address write strobe
    output wire [7:0]  ay_data_out,       // data to AY chips

    // Main ↔ Audio sound latches (to task 14)
    output wire        sound_to_main_we,  // write to main (set sound_ack)
    output wire        sound_from_main_re, // read from main (clear audio_irq)
    output wire [7:0]  sound_to_main,     // data written to main
    input  wire [7:0]  sound_from_main,   // command from main

    // Master NMI enable from main CPU's $E416 write (decocass.cpp).
    // MAME: audio NMI line asserted when (main_E416_enable AND audio_nmi_state).
    // 2026-05-17 — FIX: this was previously incorrectly wired as an OUTPUT
    // (audio_nmi_enable) that the wrapper then tried to ALSO drive from an
    // always block, creating a multi-driver scenario. Audio CPU NMI gating
    // was therefore non-functional, leaving the main CPU's $E416 write
    // ignored. This could cause sound-ack timing weirdness and potentially
    // hang BIOS waiting on audio responses.
    input  wire        audio_nmi_master_enable,

    // AUDIO-ALIVE-PROBE-2026-06-11: liveness taps for the wrapper swatch.
    // Revert: delete these 4 ports + the assign block near endmodule, and the .dbg_* connections in the wrapper.
    output wire [15:0] dbg_pc,        // current bus address (= PC at opcode fetch)
    output wire        dbg_sync,      // opcode-fetch strobe (T65 Sync)
    output wire        dbg_nmi_n,     // NMI line, active low
    output wire        dbg_nmi_en     // audio_nmi_enabled_r (BIOS armed NMI via $1000-17FF)
);

    // ========================================================================
    // T65 6502 instantiation
    // ========================================================================

    wire [15:0] cpu_addr;
    wire [7:0]  cpu_do;
    wire [7:0]  cpu_di;
    wire        cpu_rw_n;
    wire        cpu_sync;
    wire        cpu_nmi_n;

    T65 cpu (
        .Mode      (2'b00),               // 6502 mode
        .Res_n     (~reset),              // active-low reset
        .Enable    (ce_audio),            // 500 kHz clock enable
        .Clk       (clk_sys),             // 96 MHz system clock
        .Rdy       (1'b1),                // always ready
        .Abort_n   (1'b1),                // unused (65C816)
        .IRQ_n     (~audio_irq_set),      // active-low (set by main at $E414)
        .NMI_n     (cpu_nmi_n),           // active-low (from scanline counter)
        .SO_n      (1'b1),                // unused (6502 overflow)
        .R_W_n     (cpu_rw_n),            // read(1) / write(0)
        .Sync      (cpu_sync),            // opcode fetch strobe (unused here)
        .EF        (),                    // unused (65C02/816)
        .MF        (),
        .XF        (),
        .ML_n      (),
        .VP_n      (),
        .VDA       (),
        .VPA       (),
        .A         (cpu_addr),            // address bus [15:0]
        .DI        (cpu_di),              // data in (muxed from all peripherals)
        .DO        (cpu_do),              // data out
        .Regs      (),                    // debug registers (unused)
        .DEBUG     (),                    // debug port (unused)
        .NMI_ack   ()                     // debug NMI ack (unused)
    );

    // ========================================================================
    // NMI generation from scanline counter
    // ========================================================================

    reg audio_nmi_state;
    reg audio_nmi_enabled_r;

    always @(posedge clk_sys) begin
        if (reset) begin
            audio_nmi_state <= 1'b0;
            audio_nmi_enabled_r <= 1'b0;
        end else begin
            // Latch vcounter[3] at start of each scanline
            if (ce_pix && hcounter_eq_0) begin
                audio_nmi_state <= vcounter[3];
            end

            // NMI enable is set by ANY access to $1000-$17FF (read or write).
            // In hardware, this would be combinational; here we use a register
            // that's updated on CPU write and read strobes.
            // (See decocass_m.cpp lines 117-131)
            if (nmi_enable_access) begin
                audio_nmi_enabled_r <= 1'b1;
            end
        end
    end

    // AUDIO-NMI-FIX-2026-06-08: MAME audio NMI = (m_audio_nmi_enabled && m_audio_nmi_state),
    // exactly TWO terms (decocass_m.cpp:114). The old 3rd term audio_nmi_master_enable was tied to the
    // main CPU's $E416 write — but $E416 is the QUADRATURE-DECODER reset (decocass.cpp:117), NOT an
    // audio-NMI enable, so that term was never set => audio NMI held off forever => SILENT. Drop it to
    // match MAME. (audio_nmi_master_enable now unused; wrapper still drives it harmlessly.)
    // Original (3-term, wrong) below:
    // assign cpu_nmi_n = ~(audio_nmi_master_enable & audio_nmi_enabled_r & audio_nmi_state);
    assign cpu_nmi_n = ~(audio_nmi_enabled_r & audio_nmi_state);

    // ========================================================================
    // Memory decode and read/write strobes
    // ========================================================================

    wire [11:0] addr_12 = cpu_addr[11:0];  // low 12 bits for memory decode

    // Address space decode
    wire ram_sel         = (cpu_addr[15:12] == 4'h0);     // $0000-$0FFF
    wire nmi_enable_sel  = (cpu_addr[15:12] == 4'h1);     // $1000-$17FF, $1800-$1FFF
    wire ay1_data_sel    = (cpu_addr[15:12] == 4'h2);     // $2000-$2FFF
    wire ay1_addr_sel    = (cpu_addr[15:12] == 4'h4);     // $4000-$4FFF
    wire ay2_data_sel    = (cpu_addr[15:12] == 4'h6);     // $6000-$6FFF
    wire ay2_addr_sel    = (cpu_addr[15:12] == 4'h8);     // $8000-$8FFF
    wire sound_cmd_sel   = (cpu_addr[15:12] == 4'hA);     // $A000-$AFFF
    wire sound_data_sel  = (cpu_addr[15:12] == 4'hC);     // $C000-$CFFF
    wire rom_sel         = (cpu_addr[15:11] == 5'h1F);    // $F800-$FFFF

    // More precise decode within $1000-$1FFF
    // AUDIO-DECODE-WIDEN-2026-06-11: MAME arms audio NMI on ANY access to the FULL $1000-$17FF window
    // (decocass_m.cpp). The old `==8'h10` matched only $1000-$10FF, so a BIOS NMI-enable touch above
    // $10FF was missed -> NMI never armed -> silent audio CPU. Widen to $1000-$17FF (addr[15:11]==00010).
    // DIAG-REVERT-2026-06-11: restore the narrow line (commented) below; comment the wide one.
    // wire nmi_enable_reg_sel = (cpu_addr[15:8] == 8'h10);    // narrow: only $1000-$10FF (WRONG)
    wire nmi_enable_reg_sel = (cpu_addr[15:11] == 5'b00010);   // $1000-$17FF
    wire sound_ack_rst_sel  = (cpu_addr[15:8] == 8'h18); // $1800-$1FFF

    // ========================================================================
    // NMI enable and sound-ack-reset strobes
    // ========================================================================

    wire nmi_enable_access = (nmi_enable_reg_sel && (cpu_rw_n || ~cpu_rw_n)); // any access
    wire sound_ack_rst_access = (sound_ack_rst_sel && (cpu_rw_n || ~cpu_rw_n)); // any access

    // ========================================================================
    // AY chip interface strobes
    // ========================================================================

    wire ay1_write = ~cpu_rw_n;
    assign ay1_data_we = ay1_data_sel && ay1_write;
    assign ay1_addr_we = ay1_addr_sel && ay1_write;

    wire ay2_write = ~cpu_rw_n;
    assign ay2_data_we = ay2_data_sel && ay2_write;
    assign ay2_addr_we = ay2_addr_sel && ay2_write;

    assign ay_data_out = cpu_do;

    // ========================================================================
    // Main ↔ Audio sound latch interface
    // ========================================================================

    wire sound_cmd_read = sound_cmd_sel && cpu_rw_n;       // $A000 read
    wire sound_data_write = sound_data_sel && ~cpu_rw_n;   // $C000 write

    assign sound_from_main_re = sound_cmd_read;   // strobe to latch logic
    assign sound_to_main_we   = sound_data_write; // strobe to latch logic
    assign sound_to_main      = cpu_do;           // data to main

    // ========================================================================
    // Work RAM (4K SRAM)
    // ========================================================================

    wire        ram_enable = 1'b1;
    wire        ram_wren = ram_sel && ~cpu_rw_n;
    wire [7:0]  ram_dout;

    spram #(
        .address_width(12),
        .data_width(8),
        .init_file("")
    ) work_ram (
        .clock   (clk_sys),
        // AUDIO-BRAM-READ-FIX-2026-06-11: drop the `&& ce_audio` enable gate. Gating the BRAM enable with
        // ce_audio updates q ONLY on the ce edge (the same edge T65 changes the address) -> the CPU can latch a
        // STALE byte (off-by-one-ce read) -> GARBLED execution (Darksoft ran a garbled reset: no AY-init writes,
        // PC wandering in ROM fill). Un-gated: q tracks the (CE-stable) address every clk_sys, fresh by the next
        // ce; writes are idempotent (same addr/data held across the window). DIAG-REVERT-2026-06-11: restore
        // `.enable  (ram_enable && ce_audio),`.
        // .enable  (ram_enable && ce_audio),
        .enable  (1'b1),
        .address (addr_12),
        .data    (cpu_do),
        .q       (ram_dout),
        .wren    (ram_wren)
    );

    // ========================================================================
    // Audio BIOS ROM (2K, loaded via rom_loader in task 25)
    // ========================================================================

    wire [10:0] rom_addr_r = cpu_addr[10:0]; // 11-bit address for 2K ROM
    wire [7:0]  rom_dout;

    dpram #(
        .address_width(11),
        .data_width(8),
        .init_file("")
    ) audio_rom (
        .clock_a  (clk_sys),
        .enable_a (1'b1),
        .wren_a   (rom_we),
        .address_a(rom_addr_w),
        .data_a   (rom_data_w),
        .q_a      (),

        .clock_b  (clk_sys),
        // AUDIO-BRAM-READ-FIX-2026-06-11: same stale-read fix as work_ram — un-gate the CPU ROM read so the
        // instruction byte at cpu_addr is fresh by the ce edge T65 samples it (was off-by-one-ce -> garbled
        // BIOS). DIAG-REVERT-2026-06-11: restore `.enable_b (rom_sel && ce_audio),`.
        // .enable_b (rom_sel && ce_audio),
        .enable_b (1'b1),
        .wren_b   (1'b0),
        .address_b(rom_addr_r),
        .data_b   (8'h00),
        .q_b      (rom_dout)
    );

    // ========================================================================
    // CPU data input mux
    // ========================================================================

    assign cpu_di = ram_sel       ? ram_dout :
                    sound_cmd_sel ? sound_from_main :
                    rom_sel       ? rom_dout :
                    8'hFF;  // open bus

    // ========================================================================
    // NMI enable on reset (decocass_m.cpp lines 224-228)
    // ========================================================================
    // TODO(verify-with-mame): Confirm that audio NMI is disabled on reset.
    // Currently using audio_nmi_enabled_r initialized to 0. Hardware may
    // have a separate reset path. If audio NMI enable persists across resets,
    // remove the reset logic for audio_nmi_enabled_r above.

    // AUDIO-ALIVE-PROBE-2026-06-11: drive the liveness taps (revert: delete this block + the 4 ports above).
    assign dbg_pc     = cpu_addr;
    assign dbg_sync   = cpu_sync;
    assign dbg_nmi_n  = cpu_nmi_n;
    assign dbg_nmi_en = audio_nmi_enabled_r;

endmodule
